name = "ada_language_demo"
description = "Ada Language Demo"
version = "0.1.0-dev"

authors = ["Inv"]
maintainers = ["Inv <example@example.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["ada_language_demo"]
